words =
    [
        'prof.',
        'dr.',
        'drs.',
        'ds.',
        'ing.',
        'lic.',
        'mr.',
        'mw.',
        'mrs.',
        'BA',
        'BSc',
        'MA',
        'MSc',
        'MPhil',
        'PhD',
        'dr.h.c.',
        'ir.',
        'LLM',
        'bacc.',
        'cand.',
        'kand.',
        'c.',
        'mevrouw',
        'meneer',
        'de heer',
        'dhr.',
        'mvr.',
        'hr.',
    ]

File.write('titles.lst', Set.new(words).to_a.sort.join("\n").to_s)