//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.27 at 04:08:31 PM BST 
//


package org.purl.dc.terms;

import org.w3._1999._02._22_rdf_syntax_ns_.List;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}list"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/2000/01/rdf-schema#}label use="required""/>
 *       &lt;attribute name="resourceIdentifier" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "list"
})
@XmlRootElement(name = "hasVersion")
public class HasVersion {

    @XmlElement(namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", required = true)
    protected List list;
    @XmlAttribute(name = "label", namespace = "http://www.w3.org/2000/01/rdf-schema#", required = true)
    protected String label;
    @XmlAttribute(name = "resourceIdentifier", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String resourceIdentifier;

    /**
     * Gets the value of the list property.
     *
     * @return possible object is
     * {@link List }
     */
    public List getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     *
     * @param value allowed object is
     *              {@link List }
     */
    public void setList(List value) {
        this.list = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the resourceIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    /**
     * Sets the value of the resourceIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResourceIdentifier(String value) {
        this.resourceIdentifier = value;
    }

}
