package deprecated.org.crf.crf.run;


import deprecated.org.crf.crf.filters.CrfFilteredFeature;
import deprecated.org.crf.postagging.postaggers.crf.CrfPosTagger;
import deprecated.org.crf.utilities.TaggedToken;

import java.util.List;
import java.util.Set;

/**
 * Generates set of mostlikelytreefromlist to be used by the CRF algorithm for training and inference of {@link CrfPosTagger}.
 * 
 * @author Asher Stern
 * Date: Nov 10, 2014
 *
 */
public abstract class CrfFeatureGenerator<K,G>
{
	protected final Iterable<? extends List<? extends TaggedToken<K, G>>> corpus;
	protected final Set<G> tags;

	public CrfFeatureGenerator(Iterable<? extends List<? extends TaggedToken<K, G>>> corpus, Set<G> tags)
	{
		super();
		this.corpus = corpus;
		this.tags = tags;
	}

	/**
	 * Generate the mostlikelytreefromlist (to be lated retrieved by {@link #getFeatures()}).
	 */
	public abstract void generateFeatures();

	/**
	 * Return the set of mostlikelytreefromlist earlier generated by {@link #generateFeatures()}.
	 * @return the set of mostlikelytreefromlist earlier generated by {@link #generateFeatures()}.
	 */
	public abstract Set<CrfFilteredFeature<K, G>> getFeatures();
}
