//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.27 at 04:08:31 PM BST 
//


package nl.rechtspraak.schema.rechtspraak_1;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="align" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="fileref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="format" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "imagedata")
public class Imagedata {

    @XmlAttribute(name = "align", required = true)
    protected String align;
    @XmlAttribute(name = "scale")
    protected Byte scale;
    @XmlAttribute(name = "fileref", required = true)
    protected String fileref;
    @XmlAttribute(name = "depth", required = true)
    protected short depth;
    @XmlAttribute(name = "width", required = true)
    protected short width;
    @XmlAttribute(name = "format", required = true)
    protected String format;

    /**
     * Gets the value of the align property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the scale property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setScale(Byte value) {
        this.scale = value;
    }

    /**
     * Gets the value of the fileref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileref() {
        return fileref;
    }

    /**
     * Sets the value of the fileref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileref(String value) {
        this.fileref = value;
    }

    /**
     * Gets the value of the depth property.
     */
    public short getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     */
    public void setDepth(short value) {
        this.depth = value;
    }

    /**
     * Gets the value of the width property.
     */
    public short getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(short value) {
        this.width = value;
    }

    /**
     * Gets the value of the format property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormat(String value) {
        this.format = value;
    }

}
