//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.27 at 04:08:31 PM BST 
//


package nl.rechtspraak.schema.rechtspraak_1;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.rechtspraak.nl/schema/rechtspraak-1.0}imagedata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "imagedata"
})
@XmlRootElement(name = "imageobject")
public class Imageobject {

    @XmlElement(required = true)
    protected Imagedata imagedata;

    /**
     * Gets the value of the imagedata property.
     *
     * @return possible object is
     * {@link Imagedata }
     */
    public Imagedata getImagedata() {
        return imagedata;
    }

    /**
     * Sets the value of the imagedata property.
     *
     * @param value allowed object is
     *              {@link Imagedata }
     */
    public void setImagedata(Imagedata value) {
        this.imagedata = value;
    }

}
