package org.leibnizcenter.rechtspraak.markup.features;

import com.google.common.collect.Sets;
import org.leibnizcenter.rechtspraak.util.TextPattern;

import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * This code was generated automatically
 */
public class TitlesEncountered {


    public static final Set<String> titles = Sets.newHashSet(
//
// null
//
            "feiten" /*11049*/,
            "procedure" /*7921*/,
            "geding in hoger beroep" /*6681*/,
            "tenlastelegging" /*6186*/,
            "rechtsmiddel" /*5698*/,
            "geschil" /*5498*/,
            "geding in cassatie" /*4330*/,
            "vaststaande feiten" /*3357*/,
            "verdachte" /*3315*/,
            "bewezenverklaring" /*3300*/,
            "proceskosten" /*3270*/,
            "overwegingen" /*3165*/,
            "beslissing" /*3067*/,
            "voorvragen" /*3060*/,
            "uitspraak" /*3002*/,
            "geding in eerste aanleg" /*2896*/,
            "strafbaarheid van verdachte" /*2822*/,
            "toepasselijke wettelijke voorschriften" /*2555*/,
            "onderzoek van de zaak" /*2517*/,
            "onderzoek ter terechtzitting" /*2291*/,
            "strafbaarheid van de verdachte" /*2128*/,
            "verloop van de procedure" /*1631*/,
            "strafbaarheid van het feit" /*1613*/,
            "gerechtshof den haag" /*1509*/,
            "vonnis waarvan beroep" /*1188*/,
            "geding in feitelijke instanties" /*1186*/,
            "strafbaarheid van het bewezenverklaarde" /*1166*/,
            "strafoplegging" /*1085*/,
            "hd" /*1069*/,
            "geschil in hoger beroep" /*1043*/,
            "oordeel van de rechtbank" /*1034*/,
            "waardering van het bewijs" /*1032*/,
            "toepasselijke wetsartikelen" /*1014*/,
            "conclusie" /*996*/,
//,
            "geding" /*952*/,
            "strafbaarheid" /*916*/,
            "kosten" /*842*/,
            "verzoek" /*840*/,
            "rechtbank oostbrabant" /*835*/,
            "wettelijke voorschriften" /*795*/,
            "oplegging van straf enof maatregel" /*789*/,
//            "rechtbank noordnederland" /*770*/,
            "strafbaarheid van het bewezen verklaarde" /*759*/,
            "beslag" /*745*/,
            "verweer" /*701*/,
            "geschil de standpunten en conclusies van partijen" /*692*/,
            "vordering van de officier van justitie" /*691*/,
            "vordering van de benadeelde partij slachtoffer" /*675*/,
            "verdere verloop van het geding in hoger beroep" /*674*/,
            "hoger beroep" /*656*/,
            "vordering" /*645*/,
            "onderzoek op de terechtzitting" /*643*/,
            "vrijspraak" /*639*/,
            "inhoud van de tenlastelegging" /*596*/,
            "verloop van het geding" /*584*/,
            "toegepaste wettelijke bepalingen" /*581*/,
            "arrest" /*577*/,
            "kwalificatie van het bewezenverklaarde" /*559*/,
            "strafbaarheid van de feiten" /*556*/,
            "bewijs" /*555*/,
            "oplegging van straf" /*551*/,
            "benadeelde partij" /*547*/,
            "formele voorvragen" /*543*/,
            "gedaagde" /*536*/,
            "vordering van de benadeelde partij benadeelde" /*522*/,
            "toepassing van wetsartikelen" /*502*/,
            "appellant" /*499*/,
            "standpunten van partijen" /*489*/,
            "inleiding" /*480*/,
            "eiser" /*475*/,
            "toegepaste wettelijke voorschriften" /*465*/,
            "gentimeerde" /*463*/,
            "conclusies van partijen" /*439*/,
            "op te leggen straf of maatregel" /*430*/,
            "arrest van de meervoudige kamer voor strafzaken van het gerechtshof" /*428*/,
            "loop van het geding in hoger beroep" /*392*/,
            "standpunt van de verdediging" /*381*/,
            "geschil alsmede standpunten en conclusies van partijen" /*374*/,
            "beoordeling van het hoger beroep" /*368*/,
            "x te z belanghebbende" /*361*/,
            "bespreking van het cassatiemiddel" /*348*/,
            "omvang van het geschil" /*333*/,
            "vordering officier van justitie" /*311*/,
            "stukken van het geding" /*309*/,
            "verkort arrest van de meervoudige kamer voor strafzaken" /*308*/,
            "vordering van de benadeelde partij benadeelde partij" /*300*/,
            "kwalificatie" /*291*/,
            "omschrijving geschil in hoger beroep en standpunten van partijen" /*287*/,
            "a" /*281*/,
            "rechtbank gelderland" /*278*/,
            "bewijsmiddelen" /*269*/,
            "grondslag van het geschil" /*265*/,
            "proceskosten en griffierecht" /*264*/,
            "tussen partijen vaststaande feiten" /*263*/,
            "feit" /*260*/,
            "verdere verloop van de procedure" /*260*/,
            "benadeelde partijen" /*256*/,
            "uitspraak van de rechtbank luidt" /*254*/,
            "nk" /*253*/,
            "standpunt van het openbaar ministerie" /*246*/,
            "strafbaarheid van het bewezenverklaarde en de kwalificatie" /*243*/,
            "rechtbank overijssel" /*242*/,
            "ap" /*239*/,
            "vonnis" /*238*/,
            "ten aanzien van de benadeelde partij en de schadevergoedingsmaatregel" /*232*/,
            "verzoek en het verweer" /*230*/,
            "gedaagde sub" /*229*/,
            "verzoek en verweer" /*228*/,
            "schade van benadeelden" /*227*/,
            "ij" /*220*/,
            "bewijsvraag" /*216*/,
            "naam" /*215*/,
            "terbeschikkinggestelde" /*215*/,
            "geschil in conventie" /*208*/,
            "wrakingsverzoek" /*208*/,
            "geding in eerste aanleg zaaknr ha za" /*204*/,
            "standpunt van de officier van justitie" /*203*/,
            "identiteit van de opgeiste persoon" /*200*/,
            "feiten en omstandigheden" /*199*/,
            "geding in eerste aanleg zaaknr cv expl" /*198*/,
            "geding in feitelijke instantie" /*198*/,
            "beoordeling" /*196*/,
            "grondslag en inhoud van het eab" /*190*/,
            "uitspraak van de rechtbank" /*188*/,
            "vordering van de benadeelde partij" /*187*/,
            "b" /*183*/,
            "gentimeerde sub" /*182*/,
            "geschil in reconventie" /*177*/,
            "vordering tenuitvoerlegging" /*177*/,
            "ontvankelijkheid van het openbaar ministerie" /*174*/,
            "overweging met betrekking tot het bewijs" /*173*/,
            "vordering en het verweer" /*173*/,
            "rechtbank" /*169*/,
            "ontvankelijkheid van het hoger beroep" /*167*/,
            "standpunt van verzoeker" /*167*/,
            "verzoeker" /*166*/,
            "appellant sub" /*165*/,
            "arrest van de meervoudige kamer voor strafzaken" /*160*/,
            "qh" /*156*/,
            "feiten en het geding in feitelijke instanties" /*153*/,
            "appellante" /*152*/,
            "toepasselijkheid wettelijke voorschriften" /*150*/,
            "eis van de officier van justitie" /*148*/,
            "eiser sub" /*143*/,
            "tm" /*143*/,
            "bewijsoverweging" /*139*/,
            "uitgangspunten in cassatie" /*136*/,
            "verdere verloop van het geding" /*134*/,
            "inbeslaggenomen goederen" /*133*/,
            "zitting" /*132*/,
            "grieven" /*131*/,
            "en" /*129*/,
            "c" /*128*/,
            "cvg" /*127*/,
            "kwalificatie en strafbaarheid van de feiten" /*127*/,
            "standpunt van de notaris" /*127*/,
            "ontvankelijkheid" /*125*/,
            "kwalificatie en strafbaarheid van het feit" /*122*/,
            "mk" /*122*/,
//            "rechtbank noordholland" /*120*/,
            "besloten vennootschap met beperkte aansprakelijkheid" /*117*/,
            "tweede geding in cassatie" /*117*/,
            "verloop van het geding in hoger beroep" /*116*/,
            "geschil in hoger beroep en standpunten van partijen" /*113*/,
            "standpunten" /*113*/,
            "uitgangspunten" /*113*/,
            "eis officier van justitie" /*111*/,
            "vordering en verweer" /*111*/,
            "vordering van de benadeelde partij de schadevergoedingsmaatregel" /*108*/,
            "standpunt van de rechter" /*105*/,
            "vonnis in de strafzaak van" /*104*/,
            "de vader" /*103*/,
            "mondelinge behandeling van het wrakingsverzoek" /*103*/,
            "um" /*103*/,
            "de man" /*102*/,
            "eh" /*102*/,
            "geding in eerste instantie" /*102*/,
            "belanghebbende" /*100*/,
            "beoordeling van het bewijs" /*100*/,
            "hetgeen de rechtbank bewezen acht" /*99*/,
            "kwalificaties" /*99*/,
            "afdeling strafrecht" /*98*/,
            "vordering in conventie" /*98*/,
            "oplegging van straf en maatregel" /*97*/,
//            "rechtbank limburg" /*97*/,
            "vonnis van de kantonrechter" /*97*/,
            "vordering na voorwaardelijke veroordeling" /*97*/,
            "d" /*95*/,
            "eiseres" /*95*/,
            "verzoek en het verweer daartegen" /*95*/,
            "de moeder" /*94*/,
            "geding in eerste aanleg zaaknr cha za" /*92*/,
            "in reconventie" /*92*/,
            "eerste geding in cassatie" /*91*/,
            "in conventie" /*91*/,
            "strafbaarheid verdachte" /*91*/,
            "toepasselijke wetsbepalingen" /*90*/,
            "veroordeelde" /*90*/,
            "vordering van het openbaar ministerie" /*90*/,
            "rechtbank den haag" /*88*/,
            "verweerder" /*88*/,
            "de vrouw" /*87*/,
            "procesverloop" /*87*/,
            "standpunt van klager" /*86*/,
            "geding in eerste aanleg zaaknummer cv expl" /*82*/,
            "gentimeerde wonende te woonplaats" /*82*/,
            "parketnummer" /*82*/,
            "rechtbank amsterdam" /*82*/,
            "uitspraak van april" /*82*/,
            "uitspraak van de accountantskamer" /*82*/,
            "vorderingen van de benadeelde partijen" /*82*/,
            "schadevergoedingsmaatregel" /*81*/,
            "vordering tot tenuitvoerlegging" /*81*/,
            "jl" /*80*/,
            "vordering in reconventie" /*80*/,
            "bestreden uitspraak op bezwaar" /*79*/,
            "bewezenverklaring en bewijsvoering" /*79*/,
            "uitspraak waarvan herziening is gevraagd" /*79*/,
            "verzoekster" /*79*/,
            "eerste middel" /*78*/,
            "rb" /*78*/,
            "tenuitvoerlegging voorwaardelijke veroordeling" /*77*/,
            "appellant wonende te woonplaats" /*74*/,
            "redengeving bewezenverklaring" /*74*/,
            "uitspraak van de rechtbank luidt rechtdoende" /*74*/,
            "geschil en standpunten van partijen" /*73*/,
            "geschil in het incident" /*73*/,
            "nadere bewijsoverweging" /*73*/,
            "ontvankelijkheid van de officier van justitie" /*73*/,
            "rechtbank middennederland" /*73*/,
            "terechtzitting" /*73*/,
            "schadevergoeding" /*72*/,
            "verdere procedure" /*72*/,
            "standpunt van klaagster" /*71*/,
            "tweede middel" /*71*/,
            "beschikking aanslag bezwaar en geding in eerste aanleg" /*69*/,
            "benadeelde partij slachtoffer" /*68*/,
            "straf" /*68*/,
            "aanslag bezwaar en geding in eerste aanleg" /*67*/,
            "arrest van juli" /*67*/,
            "loop van het geding" /*67*/,
            "standpunten van partijen in hoger beroep" /*67*/,
            "tenlasteleggingen" /*67*/,
            "oplegging van straffen" /*66*/,
            "vordering benadeelde partij en schadevergoedingsmaatregel" /*66*/,
            "bespreking van de grieven" /*63*/,
            "ten aanzien van de feiten" /*63*/,
            "ten aanzien van feit" /*63*/,
            "aanvraag tot herziening" /*61*/,
            "verkort vonnis" /*61*/,
            "arrest van juni" /*60*/,
            "inbeslaggenomen voorwerpen" /*60*/,
            "oplegging van straf of maatregel" /*60*/,
            "overzicht" /*60*/,
            "subsidiair" /*60*/,
            "aanslag beschikking bezwaar en geding in eerste aanleg" /*58*/,
            "gerechtshof arnhemleeuwarden" /*58*/,
            "vorderingen" /*57*/,
            "arrest van maart" /*56*/,
            "betrokkene" /*56*/,
            "feiten in conventie en in reconventie" /*56*/,
            "geding in eerste aanleg zaaknr ckg za" /*56*/,
            "geding in het principaal en het incidenteel hoger beroep" /*56*/,
            "reactie van de rechter" /*56*/,
            "ciz" /*55*/,
            "geding in eerste aanleg zaaknr" /*55*/,
            "primair" /*54*/,
            "deelgeschil" /*53*/,
            "klacht" /*53*/,
            "procedure in de hoofdzaak" /*53*/,
            "tekst tenlastelegging" /*53*/,
            "vordering benadeelde partij" /*53*/,
            "artikel" /*52*/,
            "benadeelde partij en de schadevergoedingsmaatregel" /*52*/,
            "bespreking van de cassatiemiddelen" /*52*/,
            "rk" /*52*/,
            "wettelijk kader" /*52*/,
            "omvang van het hoger beroep" /*51*/,
            "geldigheid van de dagvaarding" /*50*/,
            "arrest van september" /*49*/,
            "derde middel" /*49*/,
            "handelen in strijd met artikel eerste lid van de wet wapens en munitie" /*49*/,
            "internationale kinderontvoering" /*49*/,
            "middel" /*49*/,
            "procedure in de zaak" /*49*/,
            "geschil in de hoofdzaak" /*47*/,
            "naam verdachte" /*47*/,
            "standpunt van de gerechtsdeurwaarder" /*47*/,
            "strafmaatregel" /*47*/,
            "aanhechten draagkrachtberekeningen" /*46*/,
            "arrest van april" /*46*/,
            "dcision" /*46*/,
            "motivering" /*46*/,
            "voorlopige hechtenis" /*46*/,
            "arrest van mei" /*45*/,
            "in conventie en in reconventie" /*45*/,
            "verder verloop van het geding" /*45*/,
            "beschouwing" /*44*/,
            "gronden van de beslissing" /*44*/,
            "kwalificatie en strafbaarheid van het bewezenverklaarde" /*44*/,
            "strafbaarheid feit" /*44*/,
            "bijlage" /*43*/,
            "procedure in de vrijwaringszaak" /*43*/,
            "standpunt van klagers" /*43*/,
            "verweer in conventie" /*43*/,
            "verweer in reconventie" /*43*/,
            "bedreiging met enig misdrijf tegen het leven gericht" /*42*/,
            "geding in eerste aanleg zaaknummer rolnummer" /*42*/,
            "gerechtshof sgravenhage" /*42*/,
            "strafbaarheid feiten" /*42*/,
            "verweerster" /*42*/,
            "beschikking" /*41*/,
            "mishandeling" /*41*/,
            "nw" /*41*/,
            "standpunt van de kantonrechter" /*41*/,
            "stukken" /*41*/,
            "uitspraak van de enkelvoudige kamer in de zaak tussen" /*41*/,
            "vordering in de hoofdzaak" /*41*/,
            "afdeling civiel recht" /*40*/,
            "cak" /*40*/,
            "ontvankelijkheid van het verzoek" /*40*/,
            "vonnis in de zaak van" /*40*/,
            "arrest van februari" /*39*/,
            "diefstal" /*39*/,
            "js" /*39*/,
            "behandeling in raadkamer" /*38*/,
            "beschikking in de zaak van" /*38*/,
            "doodslag" /*38*/,
            "geschil in conventie en in reconventie" /*38*/,
            "navorderingsaanslagen kwijtscheldingsbesluiten boetebeschikkingen en bezwaar" /*38*/,
            "uitspraak dd juni" /*38*/,
            "e" /*37*/,
            "eiseres sub" /*37*/,
            "geding in eerste aanleg zaaknr c kg za" /*37*/,
            "in de hoofdzaak" /*37*/,
            "uitspraak dd juli" /*37*/,
            "verwijzingsopdracht" /*37*/,
            "arrest van november" /*36*/,
            "feit primair" /*36*/,
            "vordering van de benadeelde partij aangever" /*36*/,
            "algemeen" /*35*/,
            "appellante sub" /*35*/,
            "arrest van oktober" /*35*/,
            "bewijsbeslissingen" /*35*/,
            "bijlagen" /*35*/,
            "geschil na verwijzing en standpunten van partijen" /*35*/,
            "poging tot doodslag" /*35*/,
            "rh" /*35*/,
            "staat der nederlanden ministerie van veiligheid en justitie" /*35*/,
            "vorderingen benadeelde partijen" /*35*/,
            "x" /*35*/,
            "bewijsvoering" /*34*/,
            "garantie als bedoeld in artikel eerste lid van de olw" /*34*/,
            "geding in eerste aanleg zaaknr haza" /*34*/,
            "geding in eerste aanleg zaaknr rolnr" /*34*/,
            "in beslag genomen voorwerpen" /*34*/,
            "officier van justitie heeft aangevoerd verkort en zakelijk weergegeven" /*34*/,
            "vrijspraak feit" /*34*/,
            "arrest dd april" /*33*/,
            "bevestigt de aangevallen uitspraak" /*33*/,
            "maatregel van schadevergoeding van subsidiair dagen hechtenis" /*33*/,
            "partneralimentatie" /*33*/,
            "tav parketnummer" /*33*/,
            "tenlastelegging aan de verdachte is ten laste gelegd dat" /*33*/,
            "uitspraak van juni" /*33*/,
            "vordering van de advocaatgeneraal" /*33*/,
            "x bv te z belanghebbende" /*33*/,
            "f" /*32*/,
            "ontvankelijkheid van het cassatieberoep" /*32*/,
            "ten aanzien van de benadeelde partij" /*32*/,
            "vordering van de benadeelde partij aangeefster" /*32*/,
            "aanslagen beschikkingen bezwaar en geding in eerste aanleg" /*31*/,
            "arrest van augustus" /*31*/,
            "arrest van januari" /*31*/,
            "beklag" /*31*/,
            "beschikking bezwaar en geding in eerste aanleg" /*31*/,
            "bespreking van het middel" /*31*/,
            "geding in eerste aanleg zaaknr c ha za" /*31*/,
            "geschillen" /*31*/,
            "kinderalimentatie" /*31*/,
            "openlijk in vereniging geweld plegen tegen personen" /*31*/,
            "uitspraak dd mei" /*31*/,
            "uitspraak dd oktober" /*31*/,
            "cassatiemiddel" /*30*/,
            "geschil standpunten en conclusies" /*30*/,
            "ontvankelijkheid openbaar ministerie" /*30*/,
            "verdere loop van het geding" /*30*/,
            "verloop van het proces" /*30*/,
            "vernietigt het vonnis waarvan beroep en doet opnieuw recht" /*30*/,
            "verplichting tot betaling aan de staat" /*30*/,
            "vordering in het incident" /*30*/,
            "aanduiding bestreden besluit" /*29*/,
            "arrest van december" /*29*/,
            "benadeelde partij benadeelde" /*29*/,
            "beschikkende" /*29*/,
            "feiten en het geding in feitelijke instantie" /*29*/,
            "overweegt" /*29*/,
            "proceskosten en griffierechten" /*29*/,
            "procesverbaal van de mondelinge uitspraak van de enkelvoudige kamer van" /*29*/,
            "slachtoffer" /*29*/,
            "standpunt van belanghebbenden" /*29*/,
            "standpunt van verzoekster" /*29*/,
            "straf enof de maatregel" /*29*/,
            "verder verloop van de procedure" /*29*/,
            "arrest dd maart" /*28*/,
            "feiten in beide zaken" /*28*/,
            "geding in eerste aanleg zaaknr chaza" /*28*/,
            "geding in eerste aanleg zaaknummerrolnummer ha za" /*28*/,
            "geschil en standpunten" /*28*/,
            "ingangsdatum" /*28*/,
            "inspecteur van de belastingdienstte p verweerder" /*28*/,
            "omschrijving geschil en standpunten van partijen" /*28*/,
            "standpunten van de officier van justitie en de verdediging" /*28*/,
            "tav feit" /*28*/,
            "vordering en de standpunten van partijen" /*28*/,
            "bespreking van het cassatieberoep" /*27*/,
            "de man wonende te woonplaats" /*27*/,
            "feiten in het incident" /*27*/,
            "toegepaste wetsartikelen" /*27*/,
            "uitspraak dd december" /*27*/,
            "uitspraak dd maart" /*27*/,
            "verdere geding in hoger beroep" /*27*/,
            "verzoeken" /*27*/,
            "voorgeschiedenis" /*27*/,
            "vordering van de benadeelde partij mbt het onder bewezen verklaarde" /*27*/,
            "vordering van de benadeelde partijslachtoffer" /*27*/,
            "wia" /*27*/,
            "geding na cassatie" /*26*/,
            "hof" /*26*/,
            "immaterile schadevergoeding" /*26*/,
            "incident tot tussenkomst" /*26*/,
            "proceskostenveroordeling" /*26*/,
            "schatting van het wederrechtelijk verkregen voordeel" /*26*/,
            "standpunt van gedaagde" /*26*/,
            "verweren" /*26*/,
            "eisers" /*25*/,
            "gerechtshof shertogenbosch" /*25*/,
            "geschil in voorwaardelijke reconventie" /*25*/,
            "samenstelling raadkamer en uitspraakdatum" /*25*/,
            "uitspraak dd april" /*25*/,
            "uitspraak van januari" /*25*/,
            "vaststelling van het wederrechtelijk verkregen voordeel" /*25*/,
            "verzoek en de grondslag daarvan" /*25*/,
            "vordering van de benadeelde partij betrokkene" /*25*/,
            "x wonende te z belanghebbende" /*25*/,
            "ag" /*24*/,
            "arrest dd juli" /*24*/,
            "belanghebbende sub" /*24*/,
            "geintimeerde" /*24*/,
            "geschil standpunten en conclusies van partijen" /*24*/,
            "in beslag genomen goederen" /*24*/,
            "procedure in eerste aanleg" /*24*/,
            "reactie van de rechters" /*24*/,
            "rechtbank zeelandwestbrabant" /*24*/,
            "tekst gewijzigde tenlastelegging" /*24*/,
            "terbeschikkinggestelde heeft verklaard kort en zakelijk weergegeven" /*24*/,
            "uitspraak dd augustus" /*24*/,
            "uitspraak dd september" /*24*/,
            "verdere geding" /*24*/,
            "veroordeelt de verdachte tot een gevangenisstraf voor de duur van" /*24*/,
            "vordering en het verweer in conventie" /*24*/,
            "vrijspraken" /*24*/,
            "arrest dd september" /*23*/,
            "bestreden uitspraak" /*23*/,
            "deprocedure" /*23*/,
            "geding in eerste aanleg zaaknr kg za" /*23*/,
            "geding in eerste aanleg zaaknummer ha za" /*23*/,
            "geding in eerste aanleg zaakrolnr ha za" /*23*/,
            "naam gedaagde" /*23*/,
            "oordeel van het hof" /*23*/,
            "ten aanzien van de benadeelde partijen en de schadevergoedingsmaatregel" /*23*/,
            "uitspraak van maart" /*23*/,
            "arrest dd juni" /*22*/,
            "arrest dd mei" /*22*/,
            "behandeling van de middelen" /*22*/,
            "h" /*22*/,
            "maatregel van schadevergoeding van eur subsidiair dagen hechtenis" /*22*/,
            "poging tot zware mishandeling" /*22*/,
            "stellingen van partijen" /*22*/,
            "uitspraak van juli" /*22*/,
            "verdere beoordeling van het hoger beroep" /*22*/,
            "verklaring van verdachte ter terechtzitting van juni" /*22*/,
            "weigeringsgrond als bedoeld in artikel olw" /*22*/,
            "wijziging van eis" /*22*/,
            "aanslag beschikkingen bezwaar en geding in eerste aanleg" /*21*/,
            "arrest dd februari" /*21*/,
            "conclusie van de advocaatgeneraal" /*21*/,
            "diefstal door twee of meer verenigde personen" /*21*/,
            "onschuldverweer" /*21*/,
            "standpunt van de kbvg" /*21*/,
            "toepasselijk wettelijk voorschrift" /*21*/,
            "uitspraak van mei" /*21*/,
            "verdere loop van het geding in hoger beroep" /*21*/,
            "verkort arrest van de economische kamer" /*21*/,
            "x te z hierna belanghebbende" /*21*/,
            "zw" /*21*/,
            "advies" /*20*/,
            "arrest dd januari" /*20*/,
            "bedrijf" /*20*/,
            "beschikking ontbinding arbeidsovereenkomst" /*20*/,
            "bevoegdheid van de rechtbank" /*20*/,
            "geding voor de rechtbank en het hof" /*20*/,
            "ontvankelijkheid van het openbaar ministerie in de vervolging" /*20*/,
            "overtreding van artikel van de wegenverkeerswet" /*20*/,
            "prejudicile procedure" /*20*/,
            "strafbaarheid van het bewezenverklaarde en van de verdachte" /*20*/,
            "verlenging ondertoezichtstelling en verlenging machtiging tot uithuisplaatsing" /*20*/,
            "verordening" /*20*/,
            "verslag van de advocaatgeneraal" /*20*/,
//"appellant sub en" /*19*/,
//"bedreiging met enig misdrijf tegen het leven gericht meermalen gepleegd" /*19*/,
//"beschikkingen aanslagen bezwaar en geding in eerste aanleg" /*19*/,
//"standpunt van de notarissen" /*19*/,
//"standpunt van de oudnotaris" /*19*/,
//"standpunt van eiser" /*19*/,
//"tegen deze uitspraak staat geen rechtsmiddel open" /*19*/,
//"vordering en verweer in conventie" /*19*/,
//"vordering tot schadevergoeding benadeelde partij" /*19*/,
//"vordering van de benadeelde partij slachtoffer feit" /*19*/,
//"weigeringsgrond als bedoeld in artikel eerste lid onder a olw" /*19*/,
//"adres" /*18*/,
//"arrest dd oktober" /*18*/,
//"bespreking van de klachten" /*18*/,
//"draagkracht van de man" /*18*/,
//"eendaadse samenloop van" /*18*/,
//"klager" /*18*/,
//"met betrekking tot de grieven" /*18*/,
//"noot verbalisanten" /*18*/,
//"onttrekking aan het verkeer" /*18*/,
//"op te leggen straf" /*18*/,
//"oplegging van straffen en maatregel" /*18*/,
//"standpunt van de ind en van de officier van justitie" /*18*/,
//"vierde middel" /*18*/,
//"vordering en het verweer in reconventie" /*18*/,
//"vordering van de benadeelde partijbenadeelde" /*18*/,
//"x bv statutair gevestigd te z belanghebbende" /*18*/,
//"aanslagen bezwaar en geding in eerste aanleg" /*17*/,
//"alimentatie" /*17*/,
//"feiten in conventie en reconventie" /*17*/,
//"geintimeerde sub" /*17*/,
//"geschil in hoger beroep na verwijzing" /*17*/,
//"gevangenisstraf voor de duur van maanden" /*17*/,
//"gevoerde verweren" /*17*/,
//"hoofdzaak" /*17*/,
//"met betrekking tot feit" /*17*/,
//"overweging" /*17*/,
//"rechtbank rotterdam" /*17*/,
//"rechtdoende" /*17*/,
//"uitspraak dd januari" /*17*/,
//"vermeerdering van eis" /*17*/,
//"voor een proceskostenveroordeling bestaat geen aanleiding" /*17*/,
//"x wonende te z hierna belanghebbende" /*17*/,
//"afschrift verzonden op" /*16*/,
//"appellante wonende te woonplaats" /*16*/,
//"beklaagde" /*16*/,
//"beschikking op het op juli ingekomen verzoek van" /*16*/,
//"beschikking op het op mei ingekomen verzoekschrift van" /*16*/,
//"beschouwing rechtbank" /*16*/,
//"feiten voor zover van belang in het incident" /*16*/,
//"garantie als bedoeld in artikel eerste lid olw" /*16*/,
//"geding in eerste aanleg zaakrolnr cv expl" /*16*/,
//"gedingen in hoger beroep" /*16*/,
//"inhoud van het verzoek" /*16*/,
//"juridisch kader" /*16*/,
//"meer subsidiair" /*16*/,
//"naam wonende te woonplaats" /*16*/,
//"partile vrijspraak" /*16*/,
//"procureurgeneraal bij de hoge raad der nederlanden" /*16*/,
//"rg" /*16*/,
//"standpunt van a" /*16*/,
//"standpunt van de advocaatgeneraal" /*16*/,
//"standpunt van partijen" /*16*/,
//"standpunt verdediging" /*16*/,
//"stelt als algemene voorwaarden dat de veroordeelde" /*16*/,
//"stelt als bijzondere voorwaarden dat de veroordeelde" /*16*/,
//"strafbaarheid feiten vermeld op bijlage bij de olw" /*16*/,
//"toepasselijk recht" /*16*/,
//"uitspraak dd november" /*16*/,
//"vonnis van de kantonrechter in kort geding" /*16*/,
//"vordering in voorwaardelijke reconventie" /*16*/,
//"vordering van de benadeelde partij persoon" /*16*/,
//"vordering van de benadeelde partij verbalisant" /*16*/,
//"wrakingskamer" /*16*/,
//"beschikking op het op juni ingekomen verzoek van" /*15*/,
//"beschikking van de kantonrechter" /*15*/,
//"bewijsaanbod" /*15*/,
//"bezwaar en beroep" /*15*/,
//"draagkracht" /*15*/,
//"feitelijke gang van zaken" /*15*/,
//"g" /*15*/,
//"gang van zaken" /*15*/,
//"gedaagden" /*15*/,
//"geding in eerste aanleg zaaknummer cha za" /*15*/,
//"geding na verwijzing" /*15*/,
//"grondslag van de vordering" /*15*/,
//"naam eiser" /*15*/,
//"naam van de verdachte" /*15*/,
//"scheiding" /*15*/,
//"staat der nederlanden" /*15*/,
//"standpunt van de toegevoegd kandidaatgerechtsdeurwaarder" /*15*/,
//"ten aanzien van parketnummer" /*15*/,
//"ter beschikking gestelde heeft verklaard kort en zakelijk weergegeven" /*15*/,
//"toepasselijke wettelijke bepaling" /*15*/,
//"tussenarrest van september" /*15*/,
//"uitspraak dd februari" /*15*/,
//"voorhanden stukken" /*15*/,
//"vordering en het geschil" /*15*/,
//"vordering van de benadeelde partijen" /*15*/,
//"aanleiding van het geschil" /*14*/,
//"algemeen rechtskader" /*14*/,
//"appellant en" /*14*/,
//"beschikking op het op oktober ingekomen verzoek van" /*14*/,
//"bestreden beschikking" /*14*/,
//"bv" /*14*/,
//"deelneming aan een organisatie die tot oogmerk heeft het plegen van misdrijven" /*14*/,
//"geding in eerste aanleg zaakrolnr" /*14*/,
//"geintimeerde wonende te woonplaats" /*14*/,
//"gentimeerde sub en" /*14*/,
//"gezagsuitoefening" /*14*/,
//"gronden" /*14*/,
//"inhoud van de vordering" /*14*/,
//"klacht en het verweer daartegen" /*14*/,
//"ontvankelijkheid officier van justitie" /*14*/,
//"p verweerder" /*14*/,
//"rechthebbende" /*14*/,
//"relevante regelgeving" /*14*/,
//"relevante wettelijke bepalingen" /*14*/,
//"standpunt van de inrichting" /*14*/,
//"tussenarrest van de meervoudige kamer voor strafzaken" /*14*/,
//"uitspraak van oktober" /*14*/,
//"vader" /*14*/,
//"vordering van benadeelde partij slachtoffer" /*14*/,
//"waarvan het hof uitgaat" /*14*/,
//"wijziging van omstandigheden" /*14*/,
//"arrest van de meervoudige kamer voor strafzaken van het gerechtshof te" /*13*/,
//"beantwoording van de prejudicile vragen" /*13*/,
//"behandeling van het hoger beroep" /*13*/,
//"beoordeling van het verzoek" /*13*/,
//"beschikking op het op augustus ingekomen verzoekschrift van" /*13*/,
//"beschikking op het op december ingekomen verzoek van" /*13*/,
//"bespreking van het principaal cassatieberoep" /*13*/,
//"bespreking van het principale cassatiemiddel" /*13*/,
//"bewijsverweer" /*13*/,
//"conclusies" /*13*/,
//"enof" /*13*/,
//"geldigheid dagvaarding" /*13*/,
//"gerechtshof amsterdam" /*13*/,
//"heropening van het onderzoek" /*13*/,
//"kostenveroordeling" /*13*/,
//"machtiging tot uithuisplaatsing" /*13*/,
//"naam verzoeker" /*13*/,
//"ontvankelijkheid van het verzet" /*13*/,
//"overige verweren" /*13*/,
//"rechtbank leeuwarden" /*13*/,
//"rechtbank overweegt als volgt" /*13*/,
//"schadevergoedingsmaatregel benadeelde" /*13*/,
//"standpunt van de rechters" /*13*/,
//"standpunt van de reclassering" /*13*/,
//"vaststaande feiten en de procedure in eerste aanleg" /*13*/,
//"vaststelling feiten" /*13*/,
//"verbeurdverklaring" /*13*/,
//"verdere feiten" /*13*/,
//"verweer op het zelfstandig verzoek" /*13*/,
//"verweer tevens zelfstandig verzoek" /*13*/,
//"verzoek tot verbetering" /*13*/,
//"vordering en verweer in reconventie" /*13*/,
//"vorderingen tot tenuitvoerlegging" /*13*/,
//"vorderingen van de benadeelde partijen en de schadevergoedingsmaatregel" /*13*/,
//"wwb" /*13*/,
//"zitting hebben" /*13*/,
//"ad" /*12*/,
//"ad a" /*12*/,
//"afronding" /*12*/,
//"agreement" /*12*/,
//"arrest dd december" /*12*/,
//"arrest dd november" /*12*/,
//"artikel belastbaar feit" /*12*/,
//"artikel bw" /*12*/,
//"b e s l i s s i n g" /*12*/,
//"beoordeling van het middel" /*12*/,
//"beroep is ongegrond" /*12*/,
//"beschikking op het op april ingekomen verzoek van" /*12*/,
//"beschikking op het op januari ingekomen verzoekschrift van" /*12*/,
//"beschikking op het op juni ingekomen verzoekschrift van" /*12*/,
//"beschikking op het op mei ingekomen verzoek van" /*12*/,
//"beslist" /*12*/,
//"bevoegdheid" /*12*/,
//"de pleegouders" /*12*/,
//"eiswijziging" /*12*/,
//"geding in eerste aanleg zaaknr cv" /*12*/,
//"geding na verwijzing door de hoge raad" /*12*/,
//"gerechtshof te sgravenhage" /*12*/,
//"geschil in hoger beroep en standpunten en conclusies van partijen" /*12*/,
//"in het incident" /*12*/,
//"incident tot tussenkomst dan wel voeging" /*12*/,
//"inhoud van het bezwaarschrift" /*12*/,
//"jurisprudentie" /*12*/,
//"kosten en griffierecht" /*12*/,
//"l" /*12*/,
//"mensenhandel" /*12*/,
//"omschrijving verzoek" /*12*/,
//"ontvankelijkheid van de verdachte in het hoger beroep" /*12*/,
//"overig" /*12*/,
//"rechtsmiddel tegen deze uitspraak kan binnen vier weken na de dag van verzending daarvan hoger beroep worden ingesteld bij de afdeling bestuursrechtspraak van de raad van state" /*12*/,
//"standpunt van belanghebbende" /*12*/,
//"standpunt van de raadsman" /*12*/,
//"uitspraak van augustus" /*12*/,
//"uitspraak van de voorzieningenrechter in de zaak tussen" /*12*/,
//"verdediging" /*12*/,
//"verweer van de gerechtsdeurwaarder" /*12*/,
//"verwijzingsarrest" /*12*/,
//"verzoeker sub" /*12*/,
//"vonnis in kort geding van de kantonrechter" /*12*/,
//"vordering benadeelde partij schadevergoedingsmaatregel" /*12*/,
//"vordering tenuitvoerlegging voorwaardelijke veroordeling" /*12*/,
//"vordering tot herroeping van de voorwaardelijke invrijheidstelling" /*12*/,
//"vordering van de benadeelde partij en de schadevergoedingsmaatregel" /*12*/,
//"vorderingen en grondslagen in de hoofdzaak" /*12*/,
//"vrijspraak ten aanzien van feit" /*12*/,
//"wederspannigheid" /*12*/,
//"wrakingsverzoek en het verweer" /*12*/,
//"x wonende te z eiser gemachtigde a" /*12*/,
//"afdoening" /*11*/,
//"behandeling ter terechtzitting" /*11*/,
//"belaging" /*11*/,
//"beoordeling van de zaak" /*11*/,
//"beschikking op het op april ingekomen verzoekschrift van" /*11*/,
//"beschikking op het op februari ingekomen verzoekschrift van" /*11*/,
//"beschikking op het op maart ingekomen verzoekschrift van" /*11*/,
//"besloten vennootschap" /*11*/,
//"bespreking van het principale cassatieberoep" /*11*/,
//"bureau jeugdzorg friesland" /*11*/,
//"cassatieberoep" /*11*/,
//"feiten en omstandigheden in conventie en in reconventie" /*11*/,
//"geding in eerste aanleg zaaknummer rolnummer ha za" /*11*/,
//"geding in eerste aanleg zaakrolnummer" /*11*/,
//"geding in eerste aanleg zaakrolnummer cv expl" /*11*/,
//"griffierecht" /*11*/,
//"j" /*11*/,
//"kantonrechter" /*11*/,
//"klaagster" /*11*/,
//"loop van het geding na verwijzing" /*11*/,
//"moeder" /*11*/,
//"overtreding van artikel eerste lid van de wegenverkeerswet" /*11*/,
//"overweging met betrekking tot het bewijs van feit" /*11*/,
//"proceskosten en schadevergoeding" /*11*/,
//"spoedeisend belang" /*11*/,
//"standpunt van appellante" /*11*/,
//"standpunten dexia" /*11*/,
//"ten aanzien van de tenlastelegging" /*11*/,
//"toepasselijke recht" /*11*/,
//"tussenarrest van juli" /*11*/,
//"uitspraak van de enkelvoudige kamer in het geschil tussen" /*11*/,
//"uitspraak van december" /*11*/,
//"uitspraak van november" /*11*/,
//"vermogensmaatregel" /*11*/,
//"verweer en zelfstandig verzoek" /*11*/,
//"vordering en de grondslag daarvan" /*11*/,
//"vordering en het verweer in het incident" /*11*/,
//"vordering van de benadeelde partij slachtoffer nummer" /*11*/,
//"vorderingen na voorwaardelijke veroordeling" /*11*/,
//"vorderingen van de benadeelde partijen de schadevergoedingsmaatregel" /*11*/,
//"wederrechtelijk verkregen voordeel" /*11*/,
//"als verklaring van betrokkene" /*10*/,
//"arrest dd augustus" /*10*/,
//"beantwoording van de vragen" /*10*/,
//"behandeling van het middel" /*10*/,
//"beschikking bezwaar en beroep" /*10*/,
//"beschikking op het op december ingekomen verzoekschrift van" /*10*/,
//"beschikking op het op juli ingekomen verzoekschrift van" /*10*/,
//"beschikking op het op maart ingekomen verzoek van" /*10*/,
//"beschikking op het op november ingekomen verzoek van" /*10*/,
//"beschikking op het op september ingekomen verzoekschrift van" /*10*/,
//"beslissing het hof" /*10*/,
//"beslissing inzake het bewijs" /*10*/,
//"bespreking en waardering van bewijsmiddelen" /*10*/,
//"bespreking van de middelen" /*10*/,
//"bespreking van een verweer" /*10*/,
//"bewijsverweren" /*10*/,
//"diefstal meermalen gepleegd" /*10*/,
//"feitelijke uitgangspunten" /*10*/,
//"geding in eerste aanleg zaaknrrolnr ha za" /*10*/,
//"geding in eerste aanleg zaaknummer ckg za" /*10*/,
//"geldboete van" /*10*/,
//"geschil in hoger beroep en incidenteel hoger beroep" /*10*/,
//"in de zaak met parketnummer" /*10*/,
//"in de zaak met zaaknummer" /*10*/,
//"m" /*10*/,
//"officier van justitie" /*10*/,
//"ondergetekenden" /*10*/,
//"onderzoek" /*10*/,
//"onderzoek wagner" /*10*/,
//"procedure in conventie en in reconventie" /*10*/,
//"procedures" /*10*/,
//"regelgeving wetsgeschiedenis jurisprudentie en literatuur" /*10*/,
//"schade van benadeelde" /*10*/,
//"schadevergoedingsmaatregel minderjarige zaak" /*10*/,
//"schatting van de hoogte van het wederrechtelijk verkregen voordeel" /*10*/,
//"standpunt van de rechtercommissaris" /*10*/,
//"standpunten partijen" /*10*/,
//"stelt als bijzondere voorwaarden" /*10*/,
//"strafbaarheid van de feiten en van verdachte" /*10*/,
//"terbeschikkinggestelde heeft verklaard verkort en zakelijk weergegeven" /*10*/,
//"uitspraak van februari" /*10*/,
//"valsheid in geschrift meermalen gepleegd" /*10*/,
//"verder verloop van het geding in hoger beroep" /*10*/,
//"verloop van de procedure blijkt uit" /*10*/,
//"verweer en het tegenverzoek" /*10*/,
//"voldoening op aangifte bezwaar en beroep" /*10*/,
//"vonnis in het kort geding van" /*10*/,
//"vonnis waartegen het hoger beroep is gericht" /*10*/,
//"vordering tot opheffing van de schorsing van de voorlopige hechtenis" /*10*/,
//"weigeringsgrond als bedoeld in artikel eerste lid onder a van de olw" /*10*/,
//"zorgregeling" /*10*/,
//"ad b" /*9*/,
//"adoptie" /*9*/,
//"als verklaring van verbalisant" /*9*/,
//"als verklaring van verdachte" /*9*/,
//"arrest van de economische kamer van het gerechtshof shertogenbosch" /*9*/,
//"arrest van de familiekamer dd juni" /*9*/,
//"bedreiging met zware mishandeling" /*9*/,
//"behandeling" /*9*/,
//"behandeling van de klachten" /*9*/,
//"behoefte" /*9*/,
//"belanghebbenden" /*9*/,
//"benadeelde partij minderjarige zaak" /*9*/,
//"benadeelde partij slachtoffer feit" /*9*/,
//"beoordeling van het eerste middel" /*9*/,
//"beschikking op het op augustus ingekomen verzoek van" /*9*/,
//"beschikking van juli" /*9*/,
//"beschikkingen bezwaar en geding in eerste aanleg" /*9*/,
//"bestreden uitspraken op bezwaar" /*9*/,
//"bewijsoverweging feit" /*9*/,
//"bewijsoverweging ten aanzien van feit" /*9*/,
//"draagkracht man" /*9*/,
//"ek" /*9*/,
//"feiten en" /*9*/,
//"gentimeerden" /*9*/,
//"geschil in principaal en incidenteel hoger beroep" /*9*/,
//"gevangenisstraf voor de duur van dagen" /*9*/,
//"gevangenisstraf voor de duur van jaren" /*9*/,
//"hof wijst het beklag af" /*9*/,
//"in conventie en reconventie" /*9*/,
//"inhoud van het verzoekschrift" /*9*/,
//"klacht en het verweer" /*9*/,
//"lid onder" /*9*/,
//"literatuur" /*9*/,
//"medeplegen van oplichting meermalen gepleegd" /*9*/,
//"naamloze vennootschap" /*9*/,
//"navorderingsaanslagen beschikkingen bezwaar en geding in eerste aanleg" /*9*/,
//"ondertoezichtstelling" /*9*/,
//"ontvankelijkheid van het beroep" /*9*/,
//"op te leggen maatregel" /*9*/,
//"oplichting meermalen gepleegd" /*9*/,
//"prejudicile vragen" /*9*/,
//"rechtbank amsterdamkort geding" /*9*/,
//"standpunt van de gewraakte rechters" /*9*/,
//"standpunt van de kinderrechter" /*9*/,
//"standpunt van eiseres" /*9*/,
//"standpunt van het bft" /*9*/,
//"standpunt van verzoekers" /*9*/,
//"standpunten van partijen in conventie en in reconventie" /*9*/,
//"stichting bureau jeugdzorg friesland" /*9*/,
//"tav feit subsidiair" /*9*/,
//"ten aanzien van feit van" /*9*/,
//"ter zake het verzoekschrift ex artikel a sv" /*9*/,
//"ter zake het verzoekschrift ex artikel sv" /*9*/,
//"tussenarrest van december" /*9*/,
//"tussenarrest van oktober" /*9*/,
//"uitspraken van de rechtbank" /*9*/,
//"vennootschap onder firma" /*9*/,
//"verdere beoordeling" /*9*/,
//"verweer van gedaagde" /*9*/,
//"verzet" /*9*/,
//"voorwaardelijk verzoek" /*9*/,
//"voorwaardelijke incidentele beroep" /*9*/,
//"vordering herroeping voorwaardelijke invrijheidstelling" /*9*/,
//"waardering van het bewijs ten aanzien van feit" /*9*/,
//"wao" /*9*/,
//"weigeringsgrond als bedoeld in artikel eerste lid aanhef en onder a olw" /*9*/,
//"werknemer" /*9*/,
//"witwassen" /*9*/,
//"x bv gevestigd te z belanghebbende" /*9*/,
//"aanduiding van het geschil" /*8*/,
//"aanleiding" /*8*/,
//"achtergrond van de geschillen" /*8*/,
//"algemene uiteenzetting gang van zaken en december" /*8*/,
//"algemene voorwaarden" /*8*/,
//"appellant sub wonende te woonplaats" /*8*/,
//"beantwoording van de prejudicile vraag" /*8*/,
//"beoordeling van het geschil" /*8*/,
//"beoordeling van het geschil en de motivering van de beslissing" /*8*/,
//"beschikking op het op februari ingekomen verzoek van" /*8*/,
//"beschikking van april" /*8*/,
//"beschikking van augustus" /*8*/,
//"beschikking van september" /*8*/,
//"bespreking cassatiemiddel" /*8*/,
//"bespreking van bewijsverweren" /*8*/,
//"bespreking van de gevoerde verweren" /*8*/,
//"bespreking van de verweren" /*8*/,
//"bespreking van het incidenteel cassatieberoep" /*8*/,
//"bespreking van het principaal cassatiemiddel" /*8*/,
//"bestreden besluit" /*8*/,
//"bevoegdheid van het hof" /*8*/,
//"bewijsmiddelen en de beoordeling daarvan" /*8*/,
//"bijlage i" /*8*/,
//"bijzondere bewijsoverweging" /*8*/,
//"bnb" /*8*/,
//"bureau jeugdzorg flevoland" /*8*/,
//"dochter m" /*8*/,
//"eerste middelfaalt" /*8*/,
//"eiser a" /*8*/,
//"eiser wonende te woonplaats eiser" /*8*/,
//"feiten in de hoofdzaak en in de vrijwaringszaak" /*8*/,
//"formaliteiten met betrekking tot het bewijs in alle zaken" /*8*/,
//"geding in eerste aanleg zaaknr rolnr cv expl" /*8*/,
//"geding in eerste aanleg zaaknr vv expl" /*8*/,
//"geding in eerste aanleg zaaknummer" /*8*/,
//"geldigheid van de inleidende dagvaarding" /*8*/,
//"gemeente rotterdam" /*8*/,
//"geschil na verwijzing" /*8*/,
//"gezag" /*8*/,
//"in de zaak met nummer" /*8*/,
//"in het principaal en incidenteel appel" /*8*/,
//"incident tot tussenkomst cq voeging" /*8*/,
//"inleidende beschouwingen" /*8*/,
//"inleidende opmerkingen" /*8*/,
//"kwalificatie van het bewezen verklaarde" /*8*/,
//"maatregel" /*8*/,
//"medeplegen van doodslag" /*8*/,
//"medeplegen van poging tot zware mishandeling" /*8*/,
//"mishandeling meermalen gepleegd" /*8*/,
//"naheffingsaanslag beschikking bezwaar en geding in eerste aanleg" /*8*/,
//"naheffingsaanslag bezwaar en geding in eerste aanleg" /*8*/,
//"officier van justitie bij het arrondissementsparket oostnederland" /*8*/,
//"omschrijving van het geschil" /*8*/,
//"ontvankelijkheid van het ingestelde hoger beroep" /*8*/,
//"oordeel" /*8*/,
//"oordeel van de kantonrechter" /*8*/,
//"oplegging van de maatregel" /*8*/,
//"oplegging van straf en maatregelen" /*8*/,
//"partile nietontvankelijkheid van het openbaar ministerie in de vervolging" /*8*/,
//"poging tot moord" /*8*/,
//"procesgang" /*8*/,
//"procesverbaal van de mondelinge uitspraak van de enkelvoudige kamer van november in de zaak tussen" /*8*/,
//"recapitulatie" /*8*/,
//"relevante wet en regelgeving" /*8*/,
//"relevante wetgeving" /*8*/,
//"rol van de verdachte" /*8*/,
//"schorsing vervolging" /*8*/,
//"standpunt van de gerechtsdeurwaarders" /*8*/,
//"standpunt van de gewraakte rechter" /*8*/,
//"standpunt van de kandidaatnotaris" /*8*/,
//"strafbaarheid van het feit en van verdachte" /*8*/,
//"taakstraf bestaande uit het verrichten van uren onbetaalde arbeid" /*8*/,
//"ten aanzien van het onder ten laste gelegde" /*8*/,
//"toepassing van de wetsartikelen" /*8*/,
//"tussenarrest van november" /*8*/,
//"verdere loop van de procedure" /*8*/,
//"verdere verloop van de procedure in hoger beroep" /*8*/,
//"verduistering meermalen gepleegd" /*8*/,
//"verklaring rechtsvermoeden van overlijden" /*8*/,
//"verkrachting" /*8*/,
//"verloop van de procedure in hoger beroep" /*8*/,
//"veroordeelt de verdachte tot een gevangenisstraf voor de duur van maanden" /*8*/,
//"verzoek en het standpunt van de ind" /*8*/,
//"verzoeker en verzoekster" /*8*/,
//"vooraf" /*8*/,
//"voorbedachte raad" /*8*/,
//"voortgezette handeling van" /*8*/,
//"vordering en het verweer samengevat en zakelijk weergegeven" /*8*/,
//"vordering van de benadeelde partij museum catharijneconvent" /*8*/,
//"vorderingen en het verweer" /*8*/,
//"waardering van de bewijsmiddelen" /*8*/,
//"wetgeving jurisprudentie en literatuur" /*8*/,
//"wetgeving wetsgeschiedenis jurisprudentie en literatuur" /*8*/,
//"y" /*8*/,
//"afschrift verzonden aan partijen op" /*7*/,
//"afstand van rechtsmiddelen" /*7*/,
//"arrest in dit geding" /*7*/,
//"arrest van de familiekamer dd april" /*7*/,
//"arrest van de familiekamer dd november" /*7*/,
//"artikel tarieven" /*7*/,
//"artikel van de olw" /*7*/,
//"behandeling van de zaak" /*7*/,
//"benadeelde partijen en de schadevergoedingsmaatregel" /*7*/,
//"beoordeling van het incident" /*7*/,
//"beoordeling van het principale en het incidentele hoger beroep" /*7*/,
//"beschikking op het op november ingekomen verzoekschrift van" /*7*/,
//"beschikking op het op oktober ingekomen verzoekschrift van" /*7*/,
//"beschikking op het op september ingekomen verzoek van" /*7*/,
//"beschikking van oktober" /*7*/,
//"beschikt" /*7*/,
//"beslssing" /*7*/,
//"bespreking van de cassatieklachten" /*7*/,
//"bespreking van het incidentele cassatieberoep" /*7*/,
//"bestreden tuchtuitspraak" /*7*/,
//"betrokkene betrokkene" /*7*/,
//"bewijsmiddelen feit" /*7*/,
//"bewijswaarde van de verklaringen van medeverdachte" /*7*/,
//"bijlage i bij vonnis van oktober" /*7*/,
//"bijzondere voorwaarden" /*7*/,
//"bureau jeugdzorg drenthe" /*7*/,
//"centrale raad van beroep" /*7*/,
//"dadelijke uitvoerbaarheid" /*7*/,
//"door de verdediging ingediende verzoeken" /*7*/,
//"door het hof gebruikte bewijsmiddelen" /*7*/,
//"eerste en het tweede middel" /*7*/,
//"eiser wonende te plaats eiser" /*7*/,
//"eiseres te y eiser" /*7*/,
//"en alvorens verder te beslissen" /*7*/,
//"feit en" /*7*/,
//"feiten in conventie en voorwaardelijke reconventie" /*7*/,
//"geding in eerste aanleg zaaknummer c ha za" /*7*/,
//"geding in eerste aanleg zaaknummer vv expl" /*7*/,
//"geding in eerste aanleg zaakrolnr c ha za" /*7*/,
//"geding in eerste aanleg zaakrolnummer cha za" /*7*/,
//"geding in feitelijke instanties en in cassatie" /*7*/,
//"gedoogbeleid" /*7*/,
//"gelast dat de verdachte ter beschikking wordt gesteld" /*7*/,
//"geldigheid dagvaarding en bevoegdheid rechtbank" /*7*/,
//"gemeente leiden" /*7*/,
//"genoegzaamheid van het eab" /*7*/,
//"gentimeerde wonende te woonplaats duitsland" /*7*/,
//"geschil en de procedure in eerste aanleg" /*7*/,
//"geschil in de incidenten" /*7*/,
//"geschil in eerste aanleg" /*7*/,
//"grondslag van de vordering en het verweer" /*7*/,
//"in aanmerking nemende dat" /*7*/,
//"incident tot voeging" /*7*/,
//"inleidende klacht" /*7*/,
//"k" /*7*/,
//"legt op de volgende straffen" /*7*/,
//"medeplegen" /*7*/,
//"meest subsidiair" /*7*/,
//"mensenhandel meermalen gepleegd" /*7*/,
//"mr rlh ijzerman" /*7*/,
//"naam betrokkene hierna betrokkene" /*7*/,
//"naheffingsaanslagen beschikkingen bezwaar en geding in eerste aanleg" /*7*/,
//"omvang hoger beroep" /*7*/,
//"omvang van het appel" /*7*/,
//"onder parketnummer" /*7*/,
//"onderzoek ter zitting" /*7*/,
//"ontbinding" /*7*/,
//"ontvankelijkheid in hoger beroep" /*7*/,
//"ontvankelijkheid van klager in het hoger beroep" /*7*/,
//"openbaar ministerie" /*7*/,
//"oplichting" /*7*/,
//"overwegende dat" /*7*/,
//"overwegingen ten aanzien van straf enof maatregel" /*7*/,
//"pleegouders" /*7*/,
//"prejudicile vraag" /*7*/,
//"procedure in hoger beroep" /*7*/,
//"reactie van de officier van justitie" /*7*/,
//"reactie van het openbaar ministerie" /*7*/,
//"rechtbank overweegt het volgende" /*7*/,
//"rechtsmiddel tegen deze uitspraak staat geen rechtsmiddel open" /*7*/,
//"relevante teksten en toelichtingen van de gn" /*7*/,
//"staat der nederlanden ministerie van financin" /*7*/,
//"standpunt officier van justitie" /*7*/,
//"standpunt van de gemeente" /*7*/,
//"standpunt van eisers" /*7*/,
//"stelt als bijzondere voorwaarden dat" /*7*/,
//"stichting william schrikker jeugdbescherming en jeugdreclassering" /*7*/,
//"tav feit maatregel van schadevergoeding van subsidiair dagen hechtenis" /*7*/,
//"tegenwoordig" /*7*/,
//"tenlastelegging aan de verdachte is na wijziging van de tenlastelegging ter terechtzitting ten laste gelegd dat" /*7*/,
//"tenlastelegging aan verdachte is ten laste gelegd dat" /*7*/,
//"tenuitvoerlegging voorwaardelijke veroordelingen" /*7*/,
//"teruggave" /*7*/,
//"toelichting" /*7*/,
//"toepasselijke regelgeving" /*7*/,
//"tussenarrest van februari" /*7*/,
//"van het plegen van witwassen een gewoonte maken" /*7*/,
//"vaststaande feiten in conventie en in reconventie" /*7*/,
//"verloop van de procedures" /*7*/,
//"veroordeelt de verdachte tot een gevangenisstraf voor de duur van n dag" /*7*/,
//"veroordeelt de verdachte tot een gevangenisstraf voor de duur van n week" /*7*/,
//"verplichting tot betaling" /*7*/,
//"verschenen" /*7*/,
//"verweren strekkende tot bewijsuitsluiting" /*7*/,
//"vijfde middel" /*7*/,
//"vonnis van de kantonrechter van juli" /*7*/,
//"vonnis van oktober" /*7*/,
//"voortgang van de behandeling van de zaak" /*7*/,
//"voorwaardelijke verzoeken" /*7*/,
//"vordering grondslag en verweer" /*7*/,
//"vordering tot herroeping van de voorwaardelijke invrijheidsstelling" /*7*/,
//"vordering van de benadeelde partij bedrijf" /*7*/,
//"vorderingen tenuitvoerlegging" /*7*/,
//"vraagstelling" /*7*/,
//"vragen van uitleg" /*7*/,
//"vrijspraak feit primair" /*7*/,
//"vrijspraak ten aanzien van feit slachtoffer" /*7*/,
//"vrijspraak van het primair ten laste gelegde" /*7*/,
//"vrouw" /*7*/,
//"wet en regelgeving" /*7*/,
//"wettelijke rente" /*7*/,
//"wrakingsverzoek en het standpunt van de rechter" /*7*/,
//"zware mishandeling" /*7*/,
//"a hij in de periode van juli tot en met augustus inde boerderij adres te tripscompagnie ter uitvoering van het door verdachte voorgenomen misdrijf om tezamen en in vereniging met anderen met het oogmerk om zich enof een anderen wederrechtelijk te bevoordelen door geweld enof bedreiging met geweld een persoon genaamd benadeelde te dwingen tot de afgifte van geld met dat oogmerk tezamen en in vereniging met verdachtes mededaders" /*6*/,
//"aanslag bezwaar en beroep" /*6*/,
//"aanslagen beschikkingen bezwaren en geding in eerste aanleg" /*6*/,
//"achtergrond" /*6*/,
//"achtergrond van het geschil" /*6*/,
//"afwijzing verlenging ondertoezichtstelling" /*6*/,
//"als verklaring van betrokkene afgelegd op juni" /*6*/,
//"analyse" /*6*/,
//"article echr" /*6*/,
//"artikel belastingplicht" /*6*/,
//"asielrelaas" /*6*/,
//"aw" /*6*/,
//"awb nummers en namen eisers" /*6*/,
//"behandeling van het geschil door het hof" /*6*/,
//"berechtingsrapport" /*6*/,
//"beroep" /*6*/,
//"beroep op noodweerexces" /*6*/,
//"beschikking dd augustus" /*6*/,
//"beschikking op het op januari ingekomen verzoek van" /*6*/,
//"beschikking van mei" /*6*/,
//"bespreking middel onafhankelijkheid en onpartijdigheid van de rechter" /*6*/,
//"bespreking van de overige grieven" /*6*/,
//"bespreking van het bewijsverweer" /*6*/,
//"bespreking van middel op de zaak betrekking hebbende stukken" /*6*/,
//"betrokkene feit" /*6*/,
//"bevindingen" /*6*/,
//"bewijs en bewijsvoering" /*6*/,
//"bewijsmotivering" /*6*/,
//"bijlage a" /*6*/,
//"bijlage i bij vonnis van november" /*6*/,
//"bijlage i bij vonnis van september" /*6*/,
//"college" /*6*/,
//"conclusie in het principale en incidentele cassatieberoep" /*6*/,
//"curator" /*6*/,
//"de minderjarige geboren op geboortedatum te geboorteplaats" /*6*/,
//"door de rechtbank gebruikte bewijsmiddelen" /*6*/,
//"draagkracht van de vrouw" /*6*/,
//"eigen schuld" /*6*/,
//"eisende partij" /*6*/,
//"eiser te woonplaats eiser" /*6*/,
//"fed" /*6*/,
//"feit parketnummer" /*6*/,
//"feit primair poging tot doodslag" /*6*/,
//"feiten en het geschil" /*6*/,
//"geding in eerste aanleg zaakrolnr cha za" /*6*/,
//"geding in eerste aanleg zaakrolnr ckg za" /*6*/,
//"geding in eerste aanleg zaakrolnummer ckg za" /*6*/,
//"gemeenschappelijk hof van justitie" /*6*/,
//"gentimeerde sub wonende te woonplaats" /*6*/,
//"geschil in conventie en reconventie" /*6*/,
//"geschil in de hoofdzaak en in het incident" /*6*/,
//"geschil in de vrijwaringszaak" /*6*/,
//"grief i" /*6*/,
//"identiteit veroordeelde" /*6*/,
//"in elk geval zijnde telkens handelingen waarvan hij enof zijn mededaders" /*6*/,
//"inboedel" /*6*/,
//"incident tot tussenkomst subsidiair voeging" /*6*/,
//"inkoopadministratie" /*6*/,
//"inleidende beschouwing" /*6*/,
//"inspecteur van de belastingdienstbelastingen kantoor te p verweerder" /*6*/,
//"inzake" /*6*/,
//"komen overeen dat" /*6*/,
//"machtiging tot uithuisplaatsing in een accommodatie voor gesloten jeugdzorg" /*6*/,
//"man" /*6*/,
//"medeplegen en medeplichtigheid" /*6*/,
//"michael david ilhan van waveren" /*6*/,
//"middel van de benadeelde partij" /*6*/,
//"minister van onderwijs cultuur en wetenschap verweerder" /*6*/,
//"mishandeling terwijl het feit zwaar lichamelijk letsel ten gevolge heeft" /*6*/,
//"motivering van de sancties" /*6*/,
//"n" /*6*/,
//"naamloze vennootschap sns bank nv gevestigd te utrecht" /*6*/,
//"nadere feiten" /*6*/,
//"naheffingsaanslag boetebeschikking bezwaar en geding in eerste aanleg" /*6*/,
//"navorderingsaanslag beschikking bezwaar en geding in eerste aanleg" /*6*/,
//"ntfr" /*6*/,
//"omvang van het geschil in hoger beroep" /*6*/,
//"onderlinge waarborgmaatschappij" /*6*/,
//"onrechtmatigheid ontruiming" /*6*/,
//"onttrekking aan het verkeer van de inbeslaggenomen goederen te weten" /*6*/,
//"ontvankelijkheid van het openbaar ministerie in de strafvervolging" /*6*/,
//"ontvankelijkheid van het openbaar ministerie in zijn vervolging" /*6*/,
//"ontvankelijkheid van het wrakingsverzoek" /*6*/,
//"oordeel hof" /*6*/,
//"oplegging van een maatregel" /*6*/,
//"oplegging van maatregel" /*6*/,
//"opmerking vooraf" /*6*/,
//"overweging omtrent het bewijs" /*6*/,
//"overweging van de rechtbank" /*6*/,
//"poging tot doodslag meermalen gepleegd" /*6*/,
//"proceskostenvergoeding" /*6*/,
//"processtukken" /*6*/,
//"procesverbaal van de mondelinge uitspraak van de enkelvoudige kamer van oktober in de zaak tussen" /*6*/,
//"procesverbaal van de mondelinge uitspraak van de voorzieningenrechter op" /*6*/,
//"raadsman" /*6*/,
//"reactie van de kantonrechter" /*6*/,
//"rechtbank haarlem" /*6*/,
//"rechtbank rechtdoende" /*6*/,
//"rechtsmiddel tegen deze uitspraak kan binnen zes weken na de dag van verzending daarvan hoger beroep worden ingesteld bij de centrale raad van beroep" /*6*/,
//"recidivegevaar" /*6*/,
//"redelijke termijn" /*6*/,
//"regelgeving" /*6*/,
//"samenstelling rechtbank en uitspraakdatum" /*6*/,
//"schadevergoeding nabestaande" /*6*/,
//"schriftelijke ronde standpunten vorderingen schadevergoeding" /*6*/,
//"situatie zonder ongeval" /*6*/,
//"staatssecretaris van veiligheid en justitie verweerder" /*6*/,
//"standpunt van de moeder" /*6*/,
//"stichting" /*6*/,
//"stichting pensioenfonds metaal en techniek" /*6*/,
//"strafbaarheid van de dader" /*6*/,
//"ten aanzien van de ontvankelijkheid" /*6*/,
//"totaal wederrechtelijk verkregen voordeel" /*6*/,
//"tussenarrest van januari" /*6*/,
//"tussenarrest van juni" /*6*/,
//"tweede middelfaalt" /*6*/,
//"vaststaande feiten in beide zaken" /*6*/,
//"verdere verloop van het geding in cassatie" /*6*/,
//"verloop van het onderzoek" /*6*/,
//"veroordeelt de verdachte tot een gevangenisstraf voor de duur van n jaar" /*6*/,
//"verordeningen" /*6*/,
//"vervolg van de procedure" /*6*/,
//"verweren van de verdediging" /*6*/,
//"verzoek tot uitlevering" /*6*/,
//"verzoeker hierna te noemen verzoeker" /*6*/,
//"verzoekers" /*6*/,
//"verzonden dd" /*6*/,
//"vof vof gevestigd te vestigingsplaats" /*6*/,
//"vonnis in de hoofdzaak" /*6*/,
//"vonnis in kort geding in de zaak van" /*6*/,
//"vordering tot tenuitvoerlegging in de zaak met parketnummer" /*6*/,
//"vordering van de benadeelde partij bp bedrijf" /*6*/,
//"vordering van de procureurgeneraal" /*6*/,
//"vrijspraak van feit" /*6*/,
//"vrijspraak van het onder ten laste gelegde" /*6*/,
//"waardering bewijs" /*6*/,
//"waarvan in hoger beroep moet worden uitgegaan" /*6*/,
//"wettelijk kader en wetsgeschiedenis" /*6*/,
//"wjm schram" /*6*/,
//"ww" /*6*/,
//"x wonende te z eiser" /*6*/
//
// beslissing
//
            "beslissing" /*49530*/,
            "slotsom" /*2423*/,
            "motivering van de beslissing" /*820*/,
            "gronden van de beslissing" /*694*/,
            "motivering van de beslissing in hoger beroep" /*679*/,
            "beslissing op het hoger beroep" /*221*/,
            "beslissing van de rechtbank" /*198*/,
            "beslissing verlenging terbeschikkingstelling" /*178*/,
            "geschil en de beslissing in eerste aanleg" /*125*/,
//            "beslissing inzake het bewijs" /*93*/,
//            "beslissing in kort geding" /*56*/,
//            "verdere motivering van de beslissing in hoger beroep" /*53*/,
//            "beslissingen" /*49*/,
//            "feiten het geschil en de beslissing in eerste aanleg" /*49*/,
//            "beoordeling van het geschil en de motivering van de beslissing" /*46*/,
//            "beslissing op de vordering van de benadeelde partij" /*44*/,
////,
//            "beoordeling van het verzoek en de motivering van de beslissing" /*41*/,
//            "bewijsbeslissingen" /*39*/,
//            "motivering van de beslissing na voorwaardelijke veroordeling" /*37*/,
//            "slotsom en proceskosten" /*32*/,
//            "motivering van de beslissing in het incident" /*31*/,
//            "beslissing het gerechtshof" /*28*/,
//            "vordering en de beslissing in eerste aanleg" /*28*/,
//            "beslissing op het principale en het incidentele hoger beroep" /*25*/,
//            "slotsom en kosten" /*25*/,
//            "geschil en de beslissing van de rechtbank" /*24*/,
//            "beslissing op de vordering van de benadeelde partij feit" /*23*/,
//"beslissing voorwaardelijk einde verpleging van overheidswege" /*18*/,
//"beslissing in eerste aanleg" /*17*/,
//"beslissing na voorwaardelijke veroordeling" /*17*/,
//"beslissing in het incident" /*15*/,
//"beslissing van de kantonrechter" /*15*/,
//"voortgezette motivering van de beslissing in hoger beroep" /*12*/,
//"beslissing van de voorzitter" /*11*/,
//"geschil en de beslissing van de voorzieningenrechter" /*11*/,
//"geschil en de beslissing van de kantonrechter" /*10*/,
//"vordering in eerste aanleg en de beslissing daarop" /*10*/,
//"vorderingen en de beslissing in eerste aanleg" /*10*/,
//"beslissing in conventie en in reconventie" /*9*/,
//"beslissing op de vordering van de benadeelde partij slachtoffer" /*9*/,
//"vordering en de beslissing daarop in eerste aanleg" /*9*/,
//"beslissing de rechtbank" /*8*/,
//"beslissing met betrekking tot de voorlopige hechtenis" /*8*/,
//"geschil in eerste aanleg en de beslissing van de voorzieningenrechter" /*8*/,
//"gronden voor de beslissing" /*8*/,
//"slotsom en conclusie" /*8*/,
//"beslissing in reconventie" /*7*/,
//"bestreden beslissing op bezwaar" /*7*/,
//"bewijsbeslissing" /*7*/,
//"verdere beoordeling van het geschil en de gronden van de beslissing" /*7*/,
//"verdere motivering van de beslissing" /*7*/,
//"beslissing afwijzing vordering verlenging terbeschikkingstelling" /*6*/,
//"beslissingen in eerste aanleg" /*6*/,
//"beslissingen op de vorderingen van de benadeelde partijen" /*6*/,
//"feiten het geschil en de motivering van de beslissing" /*6*/,
//"vorderingen en de beslissingen in eerste aanleg" /*6*/,
//"vorderingen in eerste aanleg en de beslissing daarop" /*6*/
//
// overwegingen
//
            "overwegingen" /*14304*/,
            "beoordeling" /*13418*/,
            "beoordeling van het geschil" /*2622*/,
            "beoordeling van het hoger beroep" /*1655*/,
            "verdere beoordeling" /*1563*/,
            "beoordeling van het bewijs" /*1516*/,
            "beoordeling van het middel" /*1375*/,
            "beoordeling van de middelen" /*899*/,
            "gronden van het hoger beroep" /*861*/,
            "motivering van de straffen en maatregelen" /*768*/,
            "gronden" /*695*/,
            "beoordeling van de ontvankelijkheid van het beroep in cassatie" /*661*/,
            "strafmotivering" /*577*/,
            "bewijsoverwegingen" /*540*/,
            "motivering van de sancties" /*409*/,
            "beoordeling van de klachten" /*403*/,
            "beoordeling van het eerste middel" /*370*/,
            "beoordeling van het tweede middel" /*303*/,
            "beoordeling van het verzoek" /*292*/,
            "beoordeling van het geschil in hoger beroep" /*290*/,
            "motivering" /*266*/,
            "beoordeling in het incident" /*226*/,
            "bewijsmiddelen en de beoordeling daarvan" /*204*/,
            "beoordeling van de ontvankelijkheid van het beroep" /*200*/,
            "overwegingen ten aanzien van straf enof maatregel" /*190*/,
            "ambtshalve beoordeling van de bestreden uitspraak" /*178*/,
            "beoordeling in conventie" /*176*/,
            "motivering van de sanctie" /*159*/,
            "beoordeling in hoger beroep" /*156*/,
            "motivering van de straf" /*156*/,
            "bewijsmotivering" /*153*/,
            "beoordeling in reconventie" /*150*/,
            "beoordeling van het derde middel" /*142*/,
            "beoordeling van de grieven" /*127*/,
            "beoordeling van de vordering" /*107*/,
            "overwegingen van de rechtbank" /*107*/,
//            "verdere beoordeling van het hoger beroep" /*107*/,
//            "geschil en de beoordeling daarvan" /*100*/,
//            "beoordeling van de ontvankelijkheid" /*98*/,
//            "beoordeling in conventie en in reconventie" /*94*/,
//            "beoordeling van de overige middelen" /*90*/,
//            "motivering van straf of maatregel" /*89*/,
//            "beoordeling van het middel in het principale beroep" /*87*/,
//            "verzoek en de gronden daarvan" /*78*/,
//            "beoordeling van de aanvraag" /*76*/,
//            "beoordeling in de hoofdzaak" /*72*/,
//            "beoordeling van de zaak" /*71*/,
//            "overwegingen ten aanzien van het bewijs" /*64*/,
//            "beoordeling van de middelen voor het overige" /*62*/,
//            "geschil en de beoordeling" /*61*/,
//            "beoordeling van het cassatieberoep" /*57*/,
//            "verdere beoordeling van het geschil" /*56*/,
//            "vordering en beoordeling in eerste aanleg" /*55*/,
//            "verzoek en de beoordeling" /*53*/,
//            "beoordeling van het vierde middel" /*52*/,
//            "motivering van de straffen" /*48*/,
//            "beoordeling van het eerste en het tweede middel" /*46*/,
//            "beoordeling van het beroep na verwijzing" /*45*/,
//            "beoordeling door de rechtbank" /*43*/,
//            "beoordeling van het in het principale beroep voorgestelde middel" /*43*/,
//            "beoordeling van het verzochte" /*42*/,
//            "motivering straf" /*42*/,
//            "beoordeling van het wrakingsverzoek" /*41*/,
//            "motivering van de hoofdelijkheid" /*41*/,
//            "beoordeling van de klacht" /*40*/,
//            "rechtsoverwegingen" /*40*/,
//            "beoordeling van de ontvankelijkheid van het verzoek tot herziening" /*39*/,
//            "beoordeling van het door de staatssecretaris voorgestelde middel" /*38*/,
//            "geschil en de beoordeling in eerste aanleg" /*37*/,
//            "overwegingen met betrekking tot het bewijs" /*37*/,
//            "motivering vrijspraak" /*35*/,
//            "overwegingen van de kantonrechter" /*35*/,
//            "verdere beoordeling in hoger beroep" /*35*/,
//            "beoordeling van het middel in het incidentele beroep" /*34*/,
//,
//            "beoordeling en de gronden daarvoor" /*31*/,
//            "beoordeling van de door belanghebbende voorgestelde middelen" /*31*/,
//            "nadere beoordeling" /*30*/,
//            "beoordeling van het vijfde middel" /*28*/,
//            "vorderingen en beoordeling in eerste aanleg" /*27*/,
//            "motivering van de straf en maatregel" /*26*/,
//            "beoordeling van het beklag" /*24*/,
//            "feiten en achtergronden" /*24*/,
//            "beoordeling van het principaal en incidenteel hoger beroep" /*23*/,
//            "grieven en de beoordeling in hoger beroep" /*23*/,
//            "nadere bewijsoverwegingen" /*23*/,
//            "beoordeling van het in het incidentele beroep voorgestelde middel" /*22*/,
//            "beoordeling van het incidentele beroep in cassatie" /*22*/,
//            "nadere bewijsmotivering" /*22*/,
//            "geschil en beoordeling" /*21*/,
//            "nadere beoordeling van het hoger beroep" /*21*/,
//            "beoordeling in conventie en reconventie" /*20*/,
//            "motivering van de maatregel" /*20*/,
//"beoordeling in de incidenten" /*19*/,
//"beoordeling van de verzoeken" /*19*/,
//"gronden van het verzoek" /*19*/,
//"vaststellingen en overwegingen" /*19*/,
//"beoordeling van de in het principale beroep voorgestelde middelen" /*18*/,
//"verdere beoordeling in conventie en in reconventie" /*18*/,
//"motivering van de straf en maatregelen" /*17*/,
//"beoordeling van het beroep" /*16*/,
//"beoordeling van het principale en het incidentele hoger beroep" /*16*/,
//"beoordeling van het tweede en het derde middel" /*16*/,
//"beoordeling van het verzet" /*16*/,
//"vordering en de beoordeling in eerste aanleg" /*16*/,
//"beoordeling in voorwaardelijke reconventie" /*15*/,
//"beschouwing en beoordeling" /*15*/,
//"standpunten van partijen en de beoordeling daarvan" /*15*/,
//"verdere beoordeling van de zaak" /*15*/,
//"beoordeling in eerste aanleg" /*14*/,
//"beoordeling van de grieven en de vordering" /*14*/,
//"beoordeling van het namens de benadeelde partij voorgestelde middel" /*14*/,
//"bijzondere overwegingen omtrent het bewijs" /*14*/,
//"gronden van het verzet" /*14*/,
//"op te leggen straf of maatregel en de gronden daarvoor" /*14*/,
//"verzoek en de beoordeling daarvan" /*14*/,
//"beoordeling in conventie en in voorwaardelijke reconventie" /*13*/,
//"beoordeling van het eerste het tweede en het derde middel" /*13*/,
//"beoordeling van het zesde middel" /*13*/,
//"gronden van het wrakingsverzoek" /*13*/,
//"beoordeling van het eerste namens de verdachte voorgestelde middel" /*12*/,
//"beoordeling van het zevende middel" /*12*/,
//"beschouwing en beoordeling van de middelen" /*12*/,
//"beoordeling in de vrijwaringszaak" /*11*/,
//"beoordeling in het incident tot verzet tegen de eiswijziging" /*11*/,
//"beoordeling van de geschillen" /*11*/,
//"beoordeling van de gronden van het verzet" /*11*/,
//"beoordeling van het incident" /*11*/,
//"beoordeling van de in het incidentele beroep voorgestelde middelen" /*10*/,
//"beoordeling van de middelen in het principale beroep" /*10*/,
//"beoordeling van de standpunten" /*10*/,
//"beoordeling van het geschil vaststaande feiten" /*10*/,
//"beoordeling van het hoger beroep na verwijzing" /*10*/,
//"beoordeling van het hoger beroep zaaknummer" /*10*/,
//"uitgangspunten voor de beoordeling" /*10*/,
//"verdere beoordeling van het geschil in hoger beroep" /*10*/,
//"beoordeling van de hoger beroepen" /*9*/,
//"beoordeling van de middelen in het principale en in het incidentele beroep" /*9*/,
//"beoordeling van de namens de verdachte voorgestelde middelen" /*9*/,
//"beoordeling van het door belanghebbende voorgestelde middel" /*9*/,
//"beoordeling van het hoger beroep en het incidenteel hoger beroep" /*9*/,
//"beoordeling van het hoger beroep in de zaak met zaaknummer" /*9*/,
//"beoordeling van het tweede namens de verdachte voorgestelde middel" /*9*/,
//"motivering van de bewezenverklaring" /*9*/,
//"motivering van de maatregel onttrekking aan het verkeer" /*9*/,
//"overwegingen van het hof" /*9*/,
//"verdere beoordeling vaststaande feiten" /*9*/,
//"vordering en beoordeling daarvan in eerste aanleg" /*9*/,
//"beoordeling van de incidentele vordering" /*8*/,
//"beoordeling van het bezwaar" /*8*/,
//"beoordeling van het cassatiemiddel" /*8*/,
//"beoordeling van het geschil in conventie en in reconventie" /*8*/,
//"beoordeling van het tiende middel" /*8*/,
//"beoordeling van het verzoek zaaknummer" /*8*/,
//"inhoudelijke beoordeling" /*8*/,
//"verdere beoordeling van het middel" /*8*/,
//"achtergronden van de zaak" /*7*/,
//"beoordeling in beide zaken" /*7*/,
//"beoordeling rechtbank" /*7*/,
//"beoordeling van de ten laste gelegde feiten" /*7*/,
//"beoordeling van de vorderingen" /*7*/,
//"beoordeling van het achtste middel" /*7*/,
//"beoordeling van het eerste het tweede het derde en het vierde middel" /*7*/,
//"beoordeling van het geschil wijziging van eis" /*7*/,
//"beoordeling van het hoger beroep en het incidentele hoger beroep" /*7*/,
//"beoordeling van het verzoek tot het vaststellen van een dwangakkoord" /*7*/,
//"bewijs en bewijsoverwegingen" /*7*/,
//"bewijsoverwegingen met betrekking tot zaaksdossier adres" /*7*/,
//"grieven en beoordeling in hoger beroep" /*7*/,
//"gronden van het wrakingsverzoek en het standpunt van verzoeker" /*7*/,
//"gronden van wraking" /*7*/,
//"motivering maatregel" /*7*/,
//"motivering van de straffen en maatregel" /*7*/,
//"nadere beoordeling van het middel" /*7*/,
//"verdere beoordeling in de hoofdzaak" /*7*/,
//"verdere beoordeling in reconventie" /*7*/,
//"algemene bewijsoverwegingen" /*6*/,
//"algemene overwegingen in alle zaken" /*6*/,
//"beoordeling in het incident en in de hoofdzaak" /*6*/,
//"beoordeling in het incident ex art rv" /*6*/,
//"beoordeling in het principaal en incidenteel appel" /*6*/,
//"beoordeling van de door de staatssecretaris voorgestelde middelen" /*6*/,
//"beoordeling van de geschillen in hoger beroep" /*6*/,
//"beoordeling van het negende middel" /*6*/,
//"beoordeling van het ten laste gelegde" /*6*/,
//"beoordeling vaststaande feiten" /*6*/,
//"beschouwing en beoordeling van het middel" /*6*/,
//"bewijsoverwegingen ten aanzien van feit" /*6*/,
//"inleidende overwegingen" /*6*/,
//"motivering van de verbeurdverklaring" /*6*/,
//"overwegingen en oordeel van het hof" /*6*/,
//"overwegingen omtrent het geschil" /*6*/,
//"tenlastelegging en motivering van de gegeven vrijspraak" /*6*/
//
// procesverloop
//
            "procesverloop" /*9511*/,
            "ontstaan en loop van het geding" /*2384*/,
            "procesverloop in hoger beroep" /*529*/,
            "procesgang" /*489*/,
            "feiten en procesverloop" /*250*/,
            "procesverloop in eerste aanleg en vaststaande feiten" /*226*/,
            "feiten en het procesverloop" /*121*/,
            "voorgeschiedenis en het procesverloop" /*111*/
//            "verdere procesverloop" /*98*/,
//            "procesverloop en de processtukken" /*93*/,
//            "ontstaan en loop van de procedure" /*45*/,
//            "ontstaan en loop van de gedingen" /*31*/
//"verder procesverloop in hoger beroep" /*19*/,
//"verdere procesverloop in hoger beroep" /*16*/,
//"inleiding feiten en procesverloop" /*10*/,
//"ontstaan en loop van het geding voor verwijzing" /*6*/


    );

    public static final Set<TextPattern> encountered = TitlesEncountered.titles.stream()
            .map(s -> new TextPattern(s, Pattern.compile(s)))
            .collect(Collectors.toSet());
}